export type Lang = "pt" | "en" | "fr" | "de";

export const LANG_LABELS: Record<Lang, string> = {
  pt: "PT",
  en: "EN",
  fr: "FR",
  de: "DE",
};

const translations = {
  // Navbar
  "nav.warehouses": { pt: "Armazéns", en: "Warehouses", fr: "Entrepôts", de: "Lager" },
  "nav.frozen": { pt: "Congelados", en: "Frozen Goods", fr: "Surgelés", de: "Tiefkühlware" },
  "nav.prepare": { pt: "Preparar Envio", en: "Prepare Shipment", fr: "Préparer l'envoi", de: "Sendung vorbereiten" },
  "nav.faq": { pt: "FAQ", en: "FAQ", fr: "FAQ", de: "FAQ" },
  "nav.contacts": { pt: "Contactos", en: "Contacts", fr: "Contacts", de: "Kontakte" },

  // Closure banner
  "closure.jan": { pt: "Encerrados de 1 a 4 de Janeiro", en: "Closed from January 1 to 4", fr: "Fermé du 1er au 4 janvier", de: "Geschlossen vom 1. bis 4. Januar" },
  "closure.apr": { pt: "Encerrados de 27 de Abril a 3 de Maio", en: "Closed from April 27 to May 3", fr: "Fermé du 27 avril au 3 mai", de: "Geschlossen vom 27. April bis 3. Mai" },
  "closure.sep": { pt: "Encerrados de 21 de Setembro a 4 de Outubro", en: "Closed from September 21 to October 4", fr: "Fermé du 21 septembre au 4 octobre", de: "Geschlossen vom 21. September bis 4. Oktober" },
  "closure.dec": { pt: "Encerrados de 20 a 31 de Dezembro", en: "Closed from December 20 to 31", fr: "Fermé du 20 au 31 décembre", de: "Geschlossen vom 20. bis 31. Dezember" },
  "closure.suffix": { pt: "Voltamos em breve!", en: "We'll be back soon!", fr: "Nous revenons bientôt !", de: "Wir sind bald zurück!" },

  // Hero
  "hero.tagline": { pt: "Há mais de 40 anos ao seu serviço", en: "Serving you for over 40 years", fr: "À votre service depuis plus de 40 ans", de: "Seit über 40 Jahren zu Ihrem Dienst" },
  "hero.title": { pt: "Portugal ⇄ Luxemburgo", en: "Portugal ⇄ Luxembourg", fr: "Portugal ⇄ Luxembourg", de: "Portugal ⇄ Luxemburg" },
  "hero.subtitle": { pt: "Transporte de mercadorias porta-a-porta com a confiança de sempre.", en: "Door-to-door freight transport you can always trust.", fr: "Transport de marchandises porte-à-porte en toute confiance.", de: "Tür-zu-Tür-Frachttransport, dem Sie vertrauen können." },

  // Smart Finder
  "finder.placeholder": { pt: "Indique-nos a sua cidade para saber as datas das nossas passagens", en: "Enter your city to find our route dates", fr: "Indiquez votre ville pour connaître nos dates de passage", de: "Geben Sie Ihre Stadt ein, um unsere Routentermine zu erfahren" },
  "finder.schedule": { pt: "Agendar recolha (WhatsApp)", en: "Schedule pickup (WhatsApp)", fr: "Planifier un enlèvement (WhatsApp)", de: "Abholung planen (WhatsApp)" },
  "finder.wa_text": { pt: "Olá! Gostaria de agendar uma recolha.", en: "Hello! I'd like to schedule a pickup.", fr: "Bonjour ! Je souhaite planifier un enlèvement.", de: "Hallo! Ich möchte eine Abholung planen." },
  "finder.ask_district": { pt: "Não encontrámos a sua cidade. Indique-nos o seu distrito:", en: "We couldn't find your city. Please select your district:", fr: "Nous n'avons pas trouvé votre ville. Indiquez votre district :", de: "Wir konnten Ihre Stadt nicht finden. Bitte wählen Sie Ihren Bezirk:" },
  "finder.not_covered": { pt: "De momento, as nossas rotas não cobrem essa zona. Contacte-nos para encontrarmos uma solução.", en: "Our routes don't currently cover that area. Contact us to find a solution.", fr: "Nos routes ne couvrent pas cette zone actuellement. Contactez-nous pour trouver une solution.", de: "Unsere Routen decken dieses Gebiet derzeit nicht ab. Kontaktieren Sie uns für eine Lösung." },
  "finder.not_found": { pt: "Não conseguimos encontrar a sua localização. Contacte-nos para mais informações:", en: "We couldn't find your location. Contact us for more information:", fr: "Nous n'avons pas pu trouver votre localisation. Contactez-nous pour plus d'informations :", de: "Wir konnten Ihren Standort nicht finden. Kontaktieren Sie uns für weitere Informationen:" },
  "finder.luxembourg": { pt: "Recolhemos e entregamos no Luxemburgo todas as semanas.", en: "We pick up and deliver in Luxembourg every week.", fr: "Nous collectons et livrons au Luxembourg chaque semaine.", de: "Wir holen ab und liefern jede Woche in Luxemburg." },
  "finder.frozen_title": { pt: "Serviço de Congelados", en: "Frozen Goods Service", fr: "Service Surgelés", de: "Tiefkühlservice" },
  "finder.frozen_dates": { pt: "Próximas datas", en: "Upcoming dates", fr: "Prochaines dates", de: "Nächste Termine" },
  "finder.near_mortagua": { pt: "A sua localização fica perto do nosso armazém de Mortágua. Se preferir, pode entregar ou levantar a sua encomenda nas nossas instalações.", en: "Your location is near our Mortágua warehouse. If you prefer, you can drop off or pick up your parcel at our facilities.", fr: "Votre localisation est proche de notre entrepôt de Mortágua. Si vous préférez, vous pouvez déposer ou retirer votre colis dans nos installations.", de: "Ihr Standort befindet sich in der Nähe unseres Lagers in Mortágua. Sie können Ihr Paket auch direkt dort abgeben oder abholen." },
  "finder.see_warehouses": { pt: "Ver os nossos armazéns", en: "See our warehouses", fr: "Voir nos entrepôts", de: "Unsere Lager ansehen" },
  "finder.all_routes": { pt: "Todas as datas - 2026", en: "All dates - 2026", fr: "Toutes les dates - 2026", de: "Alle Termine - 2026" },

  // Route descriptions
  "route.monday": { pt: "Passamos na sua zona todas as Segundas-feiras.", en: "We pass through your area every Monday.", fr: "Nous passons dans votre zone tous les lundis.", de: "Wir fahren jeden Montag durch Ihre Gegend." },
  "route.wednesday": { pt: "Passamos na sua zona 2x por semana (Quarta-feira e Sexta ou Sábado).", en: "We pass through your area twice a week (Wednesday and Friday or Saturday).", fr: "Nous passons dans votre zone 2x par semaine (mercredi et vendredi ou samedi).", de: "Wir fahren 2x pro Woche durch Ihre Gegend (Mittwoch und Freitag oder Samstag)." },
  "route.tuesday": { pt: "Passamos na sua zona todas as Terças-feiras (tarde).", en: "We pass through your area every Tuesday (afternoon).", fr: "Nous passons dans votre zone tous les mardis (après-midi).", de: "Wir fahren jeden Dienstag (nachmittags) durch Ihre Gegend." },
  "route.biweekly": { pt: "Rota Quinzenal (Sexta ou Sábado).", en: "Biweekly route (Friday or Saturday).", fr: "Route bimensuelle (vendredi ou samedi).", de: "Zweiwöchentliche Route (Freitag oder Samstag)." },
  "route.north": { pt: "Rota Norte Especial (datas específicas).", en: "Special Northern Route (specific dates).", fr: "Route Nord spéciale (dates spécifiques).", de: "Spezielle Nordroute (bestimmte Termine)." },
  "route.penacova": { pt: "Passamos na sua zona às Segundas-feiras e também na rota de Quarta/Sexta.", en: "We pass through your area on Mondays and also on the Wednesday/Friday route.", fr: "Nous passons dans votre zone les lundis et aussi sur la route mercredi/vendredi.", de: "Wir fahren montags und auch auf der Mittwoch/Freitag-Route durch Ihre Gegend." },
  "route.next_trips": { pt: "Próximas viagens", en: "Next trips", fr: "Prochains voyages", de: "Nächste Fahrten" },
  "route.next_dates": { pt: "Próximas datas", en: "Upcoming dates", fr: "Prochaines dates", de: "Nächste Termine" },

  // Features
  "feat.door_title": { pt: "Porta-a-Porta", en: "Door-to-Door", fr: "Porte-à-Porte", de: "Tür-zu-Tür" },
  "feat.door_desc": { pt: "Recolhemos e entregamos ao domicílio em toda a rota.", en: "We pick up and deliver to your home across the entire route.", fr: "Nous collectons et livrons à domicile sur tout le trajet.", de: "Wir holen ab und liefern entlang der gesamten Route." },
  "feat.years_title": { pt: "+40 Anos", en: "+40 Years", fr: "+40 Ans", de: "+40 Jahre" },
  "feat.years_desc": { pt: "Experiência e confiança na rota Portugal ⇄ Luxemburgo.", en: "Experience and trust on the Portugal ⇄ Luxembourg route.", fr: "Expérience et confiance sur la route Portugal ⇄ Luxembourg.", de: "Erfahrung und Vertrauen auf der Route Portugal ⇄ Luxemburg." },
  "feat.free_title": { pt: "Preços Imbatíveis", en: "Unbeatable Prices", fr: "Prix Imbattables", de: "Unschlagbare Preise" },
  "feat.free_desc": { pt: "Os preços mais baixos do mercado. Envios internacionais a partir de 10 €.", en: "The lowest prices on the market. International shipments from €10.", fr: "Les prix les plus bas du marché. Envois internationaux à partir de 10 €.", de: "Die niedrigsten Preise auf dem Markt. Internationale Sendungen ab 10 €." },
  "feat.coverage_title": { pt: "Várias Rotas e Armazéns", en: "Multiple Routes & Warehouses", fr: "Plusieurs Routes et Entrepôts", de: "Mehrere Routen & Lager" },
  "feat.coverage_desc": { pt: "3 armazéns + rotas que cobrem todo o Luxemburgo e 2/3 de Portugal.", en: "3 warehouses + routes covering all of Luxembourg and 2/3 of Portugal.", fr: "3 entrepôts + routes couvrant tout le Luxembourg et 2/3 du Portugal.", de: "3 Lager + Routen, die ganz Luxemburg und 2/3 von Portugal abdecken." },

  // Warehouses
  "wh.title": { pt: "Os Nossos Armazéns", en: "Our Warehouses", fr: "Nos Entrepôts", de: "Unsere Lager" },
  "wh.subtitle": { pt: "Pontos de recolha e entrega estratégicos", en: "Strategic pickup and delivery points", fr: "Points de collecte et de livraison stratégiques", de: "Strategische Abhol- und Lieferpunkte" },
  "wh.central": { pt: "Ponto Central", en: "Central Hub", fr: "Point Central", de: "Zentraler Knotenpunkt" },
  "wh.border": { pt: "Fronteira Luxemburgo", en: "Luxembourg Border", fr: "Frontière Luxembourg", de: "Grenze Luxemburg" },
  "wh.note_mortagua": { pt: "(junto ao bar Tirikeda)", en: "(next to bar Tirikeda)", fr: "(à côté du bar Tirikeda)", de: "(neben der Bar Tirikeda)" },
  "wh.note_hollerich": { pt: "(Garagens ao fundo do parque da Intralux)", en: "(Garages at the back of the Intralux park)", fr: "(Garages au fond du parc Intralux)", de: "(Garagen am Ende des Intralux-Parks)" },
  "wh.note_redange": { pt: "(fronteira de Esch 🇱🇺 com Villerupt 🇫🇷)", en: "(border of Esch 🇱🇺 with Villerupt 🇫🇷)", fr: "(frontière d'Esch 🇱🇺 avec Villerupt 🇫🇷)", de: "(Grenze von Esch 🇱🇺 mit Villerupt 🇫🇷)" },
  "wh.hours_mrt_1": { pt: "Seg-Qua: 09:00–13:00 / 15:00–19:00", en: "Mon-Wed: 09:00–13:00 / 15:00–19:00", fr: "Lun-Mer: 09:00–13:00 / 15:00–19:00", de: "Mo-Mi: 09:00–13:00 / 15:00–19:00" },
  "wh.hours_mrt_2": { pt: "Qui: 09:00–13:00", en: "Thu: 09:00–13:00", fr: "Jeu: 09:00–13:00", de: "Do: 09:00–13:00" },
  "wh.hours_mrt_3": { pt: "Sex: 14:00–18:00", en: "Fri: 14:00–18:00", fr: "Ven: 14:00–18:00", de: "Fr: 14:00–18:00" },
  "wh.hours_mrt_4": { pt: "Sáb: 09:00–13:00", en: "Sat: 09:00–13:00", fr: "Sam: 09:00–13:00", de: "Sa: 09:00–13:00" },
  "wh.hours_hol_1": { pt: "Ter: 16:00–19:00", en: "Tue: 16:00–19:00", fr: "Mar: 16:00–19:00", de: "Di: 16:00–19:00" },
  "wh.hours_hol_2": { pt: "Sáb: 10:00–17:00", en: "Sat: 10:00–17:00", fr: "Sam: 10:00–17:00", de: "Sa: 10:00–17:00" },
  "wh.hours_red_1": { pt: "Ter: 17:00–20:00", en: "Tue: 17:00–20:00", fr: "Mar: 17:00–20:00", de: "Di: 17:00–20:00" },
  "wh.hours_red_2": { pt: "Sáb: 08:00–14:00", en: "Sat: 08:00–14:00", fr: "Sam: 08:00–14:00", de: "Sa: 08:00–14:00" },
  "wh.directions": { pt: "Ver no mapa", en: "View on map", fr: "Voir sur la carte", de: "Auf der Karte anzeigen" },

  // Frozen
  "frozen.badge": { pt: "Serviço Frigorífico", en: "Refrigerated Service", fr: "Service Réfrigéré", de: "Kühltransport" },
  "frozen.title": { pt: "Congelados Portugal → Luxemburgo", en: "Frozen Goods Portugal → Luxembourg", fr: "Surgelés Portugal → Luxembourg", de: "Tiefkühlware Portugal → Luxemburg" },
  "frozen.desc": { pt: "Também oferecemos o serviço de transporte de mercadoria congelada em camião frigorífico.", en: "We also offer frozen goods transport in a refrigerated truck.", fr: "Nous offrons également le transport de marchandises surgelées en camion frigorifique.", de: "Wir bieten auch den Transport von Tiefkühlware im Kühlwagen an." },
  "frozen.dates_label": { pt: "Datas de saída 2026:", en: "2026 departure dates:", fr: "Dates de départ 2026 :", de: "Abfahrtstermine 2026:" },
  "frozen.contact": { pt: "Contactar Escritório", en: "Contact Office", fr: "Contacter le Bureau", de: "Büro kontaktieren" },
  "frozen.popup_title": { pt: "Congelados", en: "Frozen Goods", fr: "Surgelés", de: "Tiefkühlware" },
  "frozen.departure": { pt: "Saída de Portugal", en: "Departure from Portugal", fr: "Départ du Portugal", de: "Abfahrt aus Portugal" },
  "frozen.arrival": { pt: "Chegada ao Luxemburgo", en: "Arrival in Luxembourg", fr: "Arrivée au Luxembourg", de: "Ankunft in Luxemburg" },
  "frozen.schedule": { pt: "Agendar (WhatsApp)", en: "Schedule (WhatsApp)", fr: "Planifier (WhatsApp)", de: "Planen (WhatsApp)" },
  "frozen.wa_text": { pt: "Olá! Gostaria de agendar o envio de congelados para o mês de {month}.", en: "Hello! I'd like to schedule a frozen goods shipment for {month}.", fr: "Bonjour ! Je souhaite planifier un envoi de surgelés pour {month}.", de: "Hallo! Ich möchte einen Tiefkühlversand für {month} planen." },
  "frozen.more_info": { pt: "Mais informações", en: "More information", fr: "Plus d'informations", de: "Mehr Informationen" },

  // Prepare
  "prep.title": { pt: "Preparar o Envio", en: "Prepare Your Shipment", fr: "Préparer l'Envoi", de: "Sendung Vorbereiten" },
  "prep.subtitle": { pt: "O guia simplificado para que a sua mercadoria chegue em segurança.", en: "A simple guide to ensure your goods arrive safely.", fr: "Le guide simplifié pour que vos marchandises arrivent en toute sécurité.", de: "Eine einfache Anleitung, damit Ihre Ware sicher ankommt." },
  "prep.pack_title": { pt: "Embalamento", en: "Packaging", fr: "Emballage", de: "Verpackung" },
  "prep.pack_desc": { pt: "O cliente é responsável pela embalagem. Use caixas fortes e fita adesiva larga.", en: "The customer is responsible for packaging. Use strong boxes and wide tape.", fr: "Le client est responsable de l'emballage. Utilisez des boîtes solides et du ruban adhésif large.", de: "Der Kunde ist für die Verpackung verantwortlich. Verwenden Sie stabile Kartons und breites Klebeband." },
  "prep.label_title": { pt: "Identificação", en: "Labeling", fr: "Identification", de: "Kennzeichnung" },
  "prep.label_desc": { pt: "Obrigatório colocar Nome, Morada e Telefone (remetente e destinatário) em cada volume.", en: "Name, Address and Phone (sender and recipient) must be on every package.", fr: "Nom, adresse et téléphone (expéditeur et destinataire) obligatoires sur chaque colis.", de: "Name, Adresse und Telefon (Absender und Empfänger) müssen auf jedem Paket stehen." },
  "prep.fragile_title": { pt: "Frágeis", en: "Fragile Items", fr: "Fragiles", de: "Zerbrechlich" },
  "prep.fragile_desc": { pt: "TVs e eletrónicos devem ir na caixa original com proteção reforçada.", en: "TVs and electronics must be in their original box with extra protection.", fr: "Les TV et appareils électroniques doivent être dans leur boîte d'origine avec protection renforcée.", de: "Fernseher und Elektronik müssen in der Originalverpackung mit zusätzlichem Schutz sein." },
  "prep.frozen_title": { pt: "Congelados", en: "Frozen Goods", fr: "Surgelés", de: "Tiefkühlware" },
  "prep.frozen_desc": { pt: "Uso obrigatório de geleiras térmicas ou esferovite adequadas. Agende com o máximo de antecedência possível.", en: "Thermal coolers or proper polystyrene boxes are mandatory. Schedule as far in advance as possible.", fr: "L'utilisation de glacières thermiques ou de polystyrène approprié est obligatoire. Planifiez le plus tôt possible.", de: "Thermokühler oder geeignete Styroporboxen sind Pflicht. Planen Sie so früh wie möglich." },
  "prep.cta": { pt: "Contacta-nos para agendar", en: "Contact us to schedule", fr: "Contactez-nous pour planifier", de: "Kontaktieren Sie uns zur Terminvereinbarung" },
  "prep.wa_text": { pt: "Olá! Gostaria de agendar um envio.", en: "Hello! I'd like to schedule a shipment.", fr: "Bonjour ! Je souhaite planifier un envoi.", de: "Hallo! Ich möchte eine Sendung planen." },

  // FAQ
  "faq.title": { pt: "Perguntas Frequentes", en: "Frequently Asked Questions", fr: "Questions Fréquentes", de: "Häufig gestellte Fragen" },
  "faq.intro": { pt: "Estas são algumas das perguntas mais frequentes sobre o nosso serviço de transporte entre Portugal e Luxemburgo. Para situações específicas ou mercadorias especiais, recomendamos contacto direto por telefone ou WhatsApp.", en: "These are some of the most frequently asked questions about our transport service between Portugal and Luxembourg. For specific situations or special goods, we recommend direct contact by phone or WhatsApp.", fr: "Voici les questions les plus fréquentes sur notre service de transport entre le Portugal et le Luxembourg. Pour des situations spécifiques, nous recommandons un contact direct par téléphone ou WhatsApp.", de: "Dies sind einige der häufigsten Fragen zu unserem Transportdienst zwischen Portugal und Luxemburg. Für spezielle Situationen empfehlen wir direkten Kontakt per Telefon oder WhatsApp." },
  "faq.q1": { pt: "Onde entregam?", en: "Where do you deliver?", fr: "Où livrez-vous ?", de: "Wohin liefern Sie?" },
  "faq.a1": { pt: "Fazemos entregas <b>porta a porta</b>. Se o cliente preferir, também pode levantar a mercadoria nos nossos armazéns.", en: "We make <b>door-to-door</b> deliveries. If preferred, you can also pick up goods at our warehouses.", fr: "Nous effectuons des livraisons <b>porte-à-porte</b>. Si vous préférez, vous pouvez aussi retirer la marchandise dans nos entrepôts.", de: "Wir liefern <b>Tür-zu-Tür</b>. Sie können die Ware auch in unseren Lagern abholen." },
  "faq.q2": { pt: "Quando saem para Portugal ou Luxemburgo?", en: "When do you depart for Portugal or Luxembourg?", fr: "Quand partez-vous pour le Portugal ou le Luxembourg ?", de: "Wann fahren Sie nach Portugal oder Luxemburg?" },
  "faq.a2": { pt: "Saímos <b>todas as semanas</b>.<br/>Do Luxemburgo para Portugal saímos às <b>terças-feiras</b>.<br/>De Portugal para o Luxemburgo saímos às <b>quartas-feiras</b>.", en: "We depart <b>every week</b>.<br/>From Luxembourg to Portugal we leave on <b>Tuesdays</b>.<br/>From Portugal to Luxembourg we leave on <b>Wednesdays</b>.", fr: "Nous partons <b>chaque semaine</b>.<br/>Du Luxembourg vers le Portugal nous partons les <b>mardis</b>.<br/>Du Portugal vers le Luxembourg nous partons les <b>mercredis</b>.", de: "Wir fahren <b>jede Woche</b>.<br/>Von Luxemburg nach Portugal fahren wir <b>dienstags</b>.<br/>Von Portugal nach Luxemburg fahren wir <b>mittwochs</b>." },
  "faq.q3": { pt: "Como agendo uma recolha?", en: "How do I schedule a pickup?", fr: "Comment planifier un enlèvement ?", de: "Wie plane ich eine Abholung?" },
  "faq.a3": { pt: "A recolha pode ser agendada por <b>telefone ou WhatsApp</b>. Recomendamos que o agendamento seja feito com o <b>máximo de antecedência possível</b>.", en: "Pickups can be scheduled by <b>phone or WhatsApp</b>. We recommend scheduling <b>as far in advance as possible</b>.", fr: "Les enlèvements peuvent être planifiés par <b>téléphone ou WhatsApp</b>. Nous recommandons de planifier <b>le plus tôt possible</b>.", de: "Abholungen können per <b>Telefon oder WhatsApp</b> geplant werden. Wir empfehlen, <b>so früh wie möglich</b> zu buchen." },
  "faq.q4": { pt: "Fazem recolhas e entregas ao domicílio?", en: "Do you pick up and deliver to the home?", fr: "Faites-vous des collectes et livraisons à domicile ?", de: "Holen Sie ab und liefern Sie nach Hause?" },
  "faq.a4": { pt: "Sim. Fazemos recolhas e entregas diretamente na morada indicada pelo cliente, mediante <b>agendamento prévio</b>.", en: "Yes. We pick up and deliver directly to the address provided by the customer, with <b>prior scheduling</b>.", fr: "Oui. Nous collectons et livrons directement à l'adresse indiquée par le client, sur <b>rendez-vous préalable</b>.", de: "Ja. Wir holen ab und liefern direkt an die vom Kunden angegebene Adresse, mit <b>vorheriger Terminvereinbarung</b>." },
  "faq.q5": { pt: "Fazem transporte de carros e motas?", en: "Do you transport cars and motorcycles?", fr: "Transportez-vous des voitures et motos ?", de: "Transportieren Sie Autos und Motorräder?" },
  "faq.a5": { pt: "Fazemos transporte de motas, moto 4, motas de água e pequenas máquinas. <b>Não fazemos transporte de carros ligeiros nem veículos pesados,</b> entre em contacto para lhe recomendarmos empresas parceiras.", en: "We transport motorcycles, ATVs, jet skis, and small machinery. <b>We do not transport passenger cars or heavy vehicles,</b> contact us and we'll recommend partner companies.", fr: "Nous transportons motos, quads, jet-skis et petites machines. <b>Nous ne transportons pas de voitures ni de véhicules lourds,</b> contactez-nous pour des recommandations de partenaires.", de: "Wir transportieren Motorräder, ATVs, Jetskis und kleine Maschinen. <b>Wir transportieren keine PKW oder Schwerlastfahrzeuge,</b> kontaktieren Sie uns für Partnerempfehlungen." },
  "faq.q6": { pt: "Quanto tempo demora a entrega?", en: "How long does delivery take?", fr: "Combien de temps prend la livraison ?", de: "Wie lange dauert die Lieferung?" },
  "faq.a6": { pt: "O tempo de entrega depende da rota e do volume de mercadorias. Normalmente a mercadoria começa a ser entregue no destino a partir de <b>72 horas</b> após sair do país de origem.", en: "Delivery time depends on the route and volume. Normally goods start being delivered at the destination from <b>72 hours</b> after leaving the country of origin.", fr: "Le délai de livraison dépend de la route et du volume. Normalement, la livraison commence <b>72 heures</b> après le départ du pays d'origine.", de: "Die Lieferzeit hängt von Route und Volumen ab. Normalerweise beginnt die Zustellung <b>72 Stunden</b> nach Verlassen des Herkunftslandes." },
  "faq.q7": { pt: "Como devo embalar a mercadoria?", en: "How should I pack the goods?", fr: "Comment emballer la marchandise ?", de: "Wie soll ich die Ware verpacken?" },
  "faq.a7": { pt: "A mercadoria deve ser bem acondicionada em <b>caixas resistentes</b> ou embalagens adequadas. Objetos frágeis devem estar <b>devidamente protegidos</b> para evitar danos durante o transporte. A mercadoria congelada deve ser acondicionada em <b>caixas térmicas de esferovite</b> apropriadas.", en: "Goods must be well packed in <b>sturdy boxes</b> or suitable packaging. Fragile items must be <b>properly protected</b>. Frozen goods must be packed in appropriate <b>polystyrene thermal boxes</b>.", fr: "La marchandise doit être bien conditionnée dans des <b>boîtes solides</b>. Les objets fragiles doivent être <b>bien protégés</b>. Les surgelés doivent être dans des <b>boîtes en polystyrène</b>.", de: "Waren müssen in <b>stabilen Kartons</b> verpackt sein. Zerbrechliche Gegenstände müssen <b>gut geschützt</b> sein. Tiefkühlware muss in <b>Styroporboxen</b> verpackt sein." },
  "faq.q8": { pt: "Há restrições de peso ou medida?", en: "Are there weight or size restrictions?", fr: "Y a-t-il des restrictions de poids ou de taille ?", de: "Gibt es Gewichts- oder Größenbeschränkungen?" },
  "faq.a8": { pt: "Não existem restrições específicas de peso ou dimensão. No entanto, mercadorias de grande porte, como sofás, máquinas ou volumes muito grandes, exigem <b>aviso prévio no agendamento</b>.", en: "No specific weight or size restrictions. However, large items like sofas, machines or very large volumes require <b>advance notice when scheduling</b>.", fr: "Pas de restrictions spécifiques. Cependant, les objets volumineux nécessitent un <b>préavis lors de la réservation</b>.", de: "Keine spezifischen Einschränkungen. Große Gegenstände erfordern jedoch eine <b>Voranmeldung bei der Buchung</b>." },
  "faq.q9": { pt: "O que é proibido transportar?", en: "What is prohibited to transport?", fr: "Qu'est-ce qui est interdit de transporter ?", de: "Was ist verboten zu transportieren?" },
  "faq.a9": { pt: "Não transportamos: <b>explosivos, pirotecnia, animais vivos, baterias de lítio soltas, armas, substâncias ilícitas, produtos inflamáveis ou corrosivos, produtos perigosos ou mercadorias proibidas por lei</b>.<br/><br/>A mercadoria congelada não pode seguir em transporte normal.<br/><b>A mercadoria congelada deve ser comunicada previamente para que seja transportada exclusivamente no transporte frigorífico.</b>", en: "We do not transport: <b>explosives, pyrotechnics, live animals, loose lithium batteries, weapons, illicit substances, flammable or corrosive products, dangerous goods or goods prohibited by law</b>.<br/><br/>Frozen goods cannot go in normal transport.<br/><b>Frozen goods must be communicated in advance for exclusive refrigerated transport.</b>", fr: "Nous ne transportons pas : <b>explosifs, pyrotechnie, animaux vivants, batteries au lithium, armes, substances illicites, produits inflammables ou corrosifs</b>.<br/><br/><b>Les surgelés doivent être communiqués à l'avance pour le transport frigorifique.</b>", de: "Wir transportieren nicht: <b>Sprengstoff, Pyrotechnik, lebende Tiere, lose Lithiumbatterien, Waffen, illegale Substanzen, brennbare oder ätzende Produkte</b>.<br/><br/><b>Tiefkühlware muss vorab für den Kühltransport angemeldet werden.</b>" },
  "faq.q10": { pt: "Quais os métodos de pagamento?", en: "What are the payment methods?", fr: "Quels sont les modes de paiement ?", de: "Welche Zahlungsmethoden gibt es?" },
  "faq.a10": { pt: "Aceitamos pagamento em <b>numerário ou multibanco</b>. No entanto, nem todas as carrinhas dispõem de terminal multibanco, pelo que recomendamos <b>confirmar previamente</b>.", en: "We accept <b>cash or card payment</b>. However, not all vans have card terminals, so we recommend <b>confirming in advance</b>.", fr: "Nous acceptons le paiement en <b>espèces ou par carte</b>. Cependant, tous les véhicules ne disposent pas de terminal, nous recommandons de <b>confirmer à l'avance</b>.", de: "Wir akzeptieren <b>Bar- oder Kartenzahlung</b>. Da nicht alle Fahrzeuge Terminals haben, empfehlen wir, <b>vorab zu bestätigen</b>." },
  "faq.q11": { pt: "Posso enviar dinheiro ou joias?", en: "Can I send money or jewelry?", fr: "Puis-je envoyer de l'argent ou des bijoux ?", de: "Kann ich Geld oder Schmuck senden?" },
  "faq.a11": { pt: "Não recomendamos o envio de dinheiro, joias ou itens de elevado valor sem <b>declaração prévia</b>. O envio destes bens é da <b>inteira responsabilidade do cliente</b>.", en: "We do not recommend sending money, jewelry or high-value items without <b>prior declaration</b>. Sending such items is <b>entirely the customer's responsibility</b>.", fr: "Nous déconseillons l'envoi d'argent, bijoux ou objets de valeur sans <b>déclaration préalable</b>. C'est sous la <b>responsabilité du client</b>.", de: "Wir empfehlen nicht, Geld, Schmuck oder Wertgegenstände ohne <b>vorherige Erklärung</b> zu senden. Dies liegt in der <b>alleinigen Verantwortung des Kunden</b>." },

  // Footer
  "footer.title": { pt: "Contactos", en: "Contacts", fr: "Contacts", de: "Kontakte" },
  "footer.office": { pt: "Escritório - Portugal 🇵🇹", en: "Office - Portugal 🇵🇹", fr: "Bureau - Portugal 🇵🇹", de: "Büro - Portugal 🇵🇹" },
  "footer.cesar": { pt: "César - Luxemburgo 🇱🇺", en: "César - Luxembourg 🇱🇺", fr: "César - Luxembourg 🇱🇺", de: "César - Luxemburg 🇱🇺" },
  "footer.carlos": { pt: "Carlos", en: "Carlos", fr: "Carlos", de: "Carlos" },
  "footer.luis": { pt: "Luís", en: "Luís", fr: "Luís", de: "Luís" },
  "footer.copyright": { pt: "Todos os direitos reservados.", en: "All rights reserved.", fr: "Tous droits réservés.", de: "Alle Rechte vorbehalten." },
  "footer.tagline": { pt: "Mais de 40 anos na rota Portugal ⇄ Luxemburgo.", en: "Over 40 years on the Portugal ⇄ Luxembourg route.", fr: "Plus de 40 ans sur la route Portugal ⇄ Luxembourg.", de: "Über 40 Jahre auf der Route Portugal ⇄ Luxemburg." },
  "footer.regulation": { pt: "Regulamento Geral", en: "General Regulations", fr: "Règlement Général", de: "Allgemeine Geschäftsbedingungen" },

  // Regulation page
  "reg.back": { pt: "Voltar", en: "Back", fr: "Retour", de: "Zurück" },
  "reg.title": { pt: "Regulamento Geral", en: "General Regulations", fr: "Règlement Général", de: "Allgemeine Geschäftsbedingungen" },
  "reg.updated": { pt: "Última atualização", en: "Last updated", fr: "Dernière mise à jour", de: "Letzte Aktualisierung" },
  "reg.company": { pt: "Empresa", en: "Company", fr: "Entreprise", de: "Unternehmen" },

  // S1 - Objetivo
  "reg.s1_title": { pt: "Objetivo", en: "Purpose", fr: "Objectif", de: "Zweck" },
  "reg.s1_a": { pt: "O presente regulamento define as condições de funcionamento, responsabilidades, direitos e deveres aplicáveis aos serviços prestados pela empresa TRANSPORTES CARLOS & CÉSAR, que opera serviços de transporte e logística entre Portugal, Luxemburgo e outros países da União Europeia.", en: "These regulations define the operating conditions, responsibilities, rights and duties applicable to the services provided by TRANSPORTES CARLOS & CÉSAR, which operates transport and logistics services between Portugal, Luxembourg and other European Union countries.", fr: "Le présent règlement définit les conditions de fonctionnement, responsabilités, droits et devoirs applicables aux services fournis par TRANSPORTES CARLOS & CÉSAR, qui opère des services de transport et logistique entre le Portugal, le Luxembourg et d'autres pays de l'Union européenne.", de: "Diese Verordnung definiert die Betriebsbedingungen, Verantwortlichkeiten, Rechte und Pflichten für die Dienstleistungen von TRANSPORTES CARLOS & CÉSAR, die Transport- und Logistikdienste zwischen Portugal, Luxemburg und anderen EU-Ländern betreibt." },
  "reg.s1_b": { pt: "A utilização dos serviços da empresa implica a aceitação integral das presentes condições.", en: "The use of the company's services implies full acceptance of these conditions.", fr: "L'utilisation des services de l'entreprise implique l'acceptation intégrale des présentes conditions.", de: "Die Nutzung der Dienstleistungen des Unternehmens impliziert die vollständige Akzeptanz dieser Bedingungen." },

  // S2 - Agendamentos de Recolhas
  "reg.s2_title": { pt: "Agendamentos de Recolhas", en: "Pickup Scheduling", fr: "Planification des Enlèvements", de: "Abholtermine" },
  "reg.s2_a": { pt: "As recolhas devem ser agendadas com o máximo de antecedência possível.", en: "Pickups must be scheduled as far in advance as possible.", fr: "Les enlèvements doivent être planifiés le plus tôt possible.", de: "Abholungen müssen so früh wie möglich geplant werden." },
  "reg.s2_b": { pt: "O agendamento pode ser realizado através dos seguintes meios: telefone, WhatsApp, ou outros meios de contacto disponibilizados pela empresa.", en: "Scheduling can be done via: phone, WhatsApp, or other contact methods provided by the company.", fr: "La planification peut se faire par : téléphone, WhatsApp, ou d'autres moyens de contact fournis par l'entreprise.", de: "Die Terminplanung kann über Telefon, WhatsApp oder andere vom Unternehmen bereitgestellte Kontaktmittel erfolgen." },
  "reg.s2_c": { pt: "O cliente deve fornecer informações corretas e completas, nomeadamente: nome do remetente, contacto telefónico, morada de recolha, morada de entrega, número de volumes, descrição da mercadoria e peso aproximado.", en: "The customer must provide correct and complete information, namely: sender's name, phone contact, pickup address, delivery address, number of packages, description of goods and approximate weight.", fr: "Le client doit fournir des informations correctes et complètes, notamment : nom de l'expéditeur, contact téléphonique, adresse d'enlèvement, adresse de livraison, nombre de colis, description de la marchandise et poids approximatif.", de: "Der Kunde muss korrekte und vollständige Angaben machen: Name des Absenders, Telefonnummer, Abholadresse, Lieferadresse, Anzahl der Pakete, Warenbeschreibung und ungefähres Gewicht." },
  "reg.s2_d": { pt: "A empresa não se responsabiliza por atrasos ou impossibilidade de entrega resultantes de informações incorretas ou incompletas fornecidas pelo cliente.", en: "The company is not responsible for delays or delivery failures resulting from incorrect or incomplete information provided by the customer.", fr: "L'entreprise n'est pas responsable des retards ou de l'impossibilité de livraison résultant d'informations incorrectes ou incomplètes fournies par le client.", de: "Das Unternehmen haftet nicht für Verzögerungen oder Zustellungsfehler aufgrund falscher oder unvollständiger Kundenangaben." },

  // S3 - Embalamento
  "reg.s3_title": { pt: "Embalamento e Responsabilidade do Cliente", en: "Packaging and Customer Responsibility", fr: "Emballage et Responsabilité du Client", de: "Verpackung und Kundenverantwortung" },
  "reg.s3_a": { pt: "A mercadoria deve estar devidamente embalada, protegida e identificada.", en: "Goods must be properly packaged, protected and labeled.", fr: "La marchandise doit être correctement emballée, protégée et identifiée.", de: "Die Ware muss ordnungsgemäß verpackt, geschützt und gekennzeichnet sein." },
  "reg.s3_b": { pt: "Cada volume deve conter: nome do remetente, nome do destinatário, morada de entrega e contacto telefónico.", en: "Each package must contain: sender's name, recipient's name, delivery address and phone contact.", fr: "Chaque colis doit contenir : nom de l'expéditeur, nom du destinataire, adresse de livraison et contact téléphonique.", de: "Jedes Paket muss enthalten: Name des Absenders, Name des Empfängers, Lieferadresse und Telefonnummer." },
  "reg.s3_c": { pt: "O cliente é responsável pela adequação da embalagem ao tipo de mercadoria transportada.", en: "The customer is responsible for ensuring the packaging is suitable for the type of goods transported.", fr: "Le client est responsable de l'adéquation de l'emballage au type de marchandise transportée.", de: "Der Kunde ist dafür verantwortlich, dass die Verpackung für die Art der transportierten Ware geeignet ist." },
  "reg.s3_d": { pt: "A empresa não se responsabiliza por danos causados por embalamento inadequado.", en: "The company is not responsible for damage caused by inadequate packaging.", fr: "L'entreprise n'est pas responsable des dommages causés par un emballage inadéquat.", de: "Das Unternehmen haftet nicht für Schäden durch unzureichende Verpackung." },
  "reg.s3_e": { pt: "Produtos frágeis devem estar devidamente protegidos.", en: "Fragile products must be properly protected.", fr: "Les produits fragiles doivent être correctement protégés.", de: "Zerbrechliche Produkte müssen ordnungsgemäß geschützt werden." },
  "reg.s3_f": { pt: "Alimentos congelados devem ser transportados em geleiras ou caixas térmicas apropriadas, sendo da responsabilidade do cliente garantir as condições adequadas de conservação.", en: "Frozen food must be transported in appropriate coolers or thermal boxes; the customer is responsible for ensuring proper preservation conditions.", fr: "Les aliments surgelés doivent être transportés dans des glacières ou boîtes thermiques appropriées, le client étant responsable de garantir les conditions de conservation adéquates.", de: "Tiefkühlkost muss in geeigneten Kühltaschen oder Thermoboxen transportiert werden; der Kunde ist für die Gewährleistung angemessener Lagerbedingungen verantwortlich." },

  // S4 - Pagamento
  "reg.s4_title": { pt: "Formas de Pagamento", en: "Payment Methods", fr: "Modes de Paiement", de: "Zahlungsmethoden" },
  "reg.s4_a": { pt: "O pagamento do serviço pode ser realizado através de: numerário, multibanco (quando disponível), ou outros métodos disponibilizados pela empresa.", en: "Payment can be made via: cash, card (when available), or other methods provided by the company.", fr: "Le paiement peut être effectué par : espèces, carte bancaire (si disponible), ou d'autres méthodes fournies par l'entreprise.", de: "Die Zahlung kann erfolgen durch: Bargeld, Karte (wenn verfügbar) oder andere vom Unternehmen bereitgestellte Methoden." },
  "reg.s4_b": { pt: "Nem todas as viaturas dispõem de terminal de pagamento.", en: "Not all vehicles are equipped with a payment terminal.", fr: "Tous les véhicules ne disposent pas d'un terminal de paiement.", de: "Nicht alle Fahrzeuge sind mit einem Zahlungsterminal ausgestattet." },
  "reg.s4_c": { pt: "O pagamento deve ser efetuado no momento da recolha ou da entrega, conforme acordado no momento da reserva.", en: "Payment must be made at the time of pickup or delivery, as agreed at the time of booking.", fr: "Le paiement doit être effectué au moment de l'enlèvement ou de la livraison, selon l'accord lors de la réservation.", de: "Die Zahlung muss bei Abholung oder Lieferung erfolgen, wie bei der Buchung vereinbart." },
  "reg.s4_d": { pt: "Em caso de não pagamento, a empresa reserva-se ao direito de reter a mercadoria até à regularização do valor em dívida.", en: "In case of non-payment, the company reserves the right to retain the goods until the outstanding amount is settled.", fr: "En cas de non-paiement, l'entreprise se réserve le droit de retenir la marchandise jusqu'à la régularisation du montant dû.", de: "Bei Nichtzahlung behält sich das Unternehmen das Recht vor, die Ware bis zur Begleichung des ausstehenden Betrags einzubehalten." },

  // S5 - Cancelamentos
  "reg.s5_title": { pt: "Cancelamentos e Alterações", en: "Cancellations and Changes", fr: "Annulations et Modifications", de: "Stornierungen und Änderungen" },
  "reg.s5_a": { pt: "O cliente pode cancelar ou alterar uma recolha sem custos, desde que a comunicação seja efetuada com antecedência razoável.", en: "The customer may cancel or modify a pickup at no cost, provided notice is given with reasonable advance.", fr: "Le client peut annuler ou modifier un enlèvement sans frais, à condition de prévenir dans un délai raisonnable.", de: "Der Kunde kann eine Abholung kostenlos stornieren oder ändern, sofern dies mit angemessener Vorankündigung erfolgt." },
  "reg.s5_b": { pt: "Cancelamentos ou alterações de última hora podem implicar custos administrativos ou logísticos, dependendo do estado do serviço.", en: "Last-minute cancellations or changes may incur administrative or logistical costs, depending on the service status.", fr: "Les annulations ou modifications de dernière minute peuvent entraîner des frais administratifs ou logistiques, selon l'état du service.", de: "Kurzfristige Stornierungen oder Änderungen können je nach Servicestatus Verwaltungs- oder Logistikkosten nach sich ziehen." },

  // S6 - Transporte e Entregas
  "reg.s6_title": { pt: "Transporte e Entregas", en: "Transport and Deliveries", fr: "Transport et Livraisons", de: "Transport und Lieferungen" },
  "reg.s6_intro": { pt: "Os prazos de entrega são estimativos e podem variar conforme: distância, condições de trânsito, condições meteorológicas e procedimentos logísticos.", en: "Delivery times are estimates and may vary depending on: distance, traffic conditions, weather conditions and logistics procedures.", fr: "Les délais de livraison sont indicatifs et peuvent varier selon : la distance, les conditions de circulation, les conditions météorologiques et les procédures logistiques.", de: "Lieferzeiten sind Schätzungen und können je nach Entfernung, Verkehrslage, Wetterbedingungen und Logistikverfahren variieren." },
  "reg.s6_a": { pt: "Os motoristas não estão autorizados a: abrir mercadorias, montar ou desmontar equipamentos, instalar produtos, entrar em residências, subir escadas de edifícios ou transportar mercadorias até divisões interiores.", en: "Drivers are not authorized to: open goods, assemble or disassemble equipment, install products, enter residences, climb building stairs or carry goods to interior rooms.", fr: "Les chauffeurs ne sont pas autorisés à : ouvrir les marchandises, monter ou démonter des équipements, installer des produits, entrer dans les résidences, monter les escaliers des immeubles ou transporter des marchandises jusqu'aux pièces intérieures.", de: "Fahrer sind nicht befugt: Waren zu öffnen, Geräte auf- oder abzubauen, Produkte zu installieren, Wohnungen zu betreten, Gebäudetreppen zu steigen oder Waren in Innenräume zu tragen." },
  "reg.s6_b": { pt: "As entregas são realizadas à porta do prédio, moradia ou local indicado pelo cliente.", en: "Deliveries are made at the building entrance, house or location indicated by the customer.", fr: "Les livraisons sont effectuées à la porte de l'immeuble, de la maison ou du lieu indiqué par le client.", de: "Lieferungen erfolgen am Gebäudeeingang, Haus oder vom Kunden angegebenen Ort." },
  "reg.s6_c": { pt: "Caso o destinatário esteja ausente, não atenda chamadas ou os dados estejam incorretos, a mercadoria poderá: regressar ao armazém, ser reprogramada para nova entrega ou ficar disponível para recolha.", en: "If the recipient is absent, does not answer calls or the data is incorrect, the goods may: return to the warehouse, be rescheduled for a new delivery or be made available for collection.", fr: "Si le destinataire est absent, ne répond pas aux appels ou si les données sont incorrectes, la marchandise pourra : retourner à l'entrepôt, être reprogrammée pour une nouvelle livraison ou être mise à disposition pour retrait.", de: "Wenn der Empfänger abwesend ist, Anrufe nicht beantwortet oder die Daten falsch sind, kann die Ware: ins Lager zurückkehren, für eine neue Lieferung umgeplant oder zur Abholung bereitgestellt werden." },
  "reg.s6_d": { pt: "Custos adicionais poderão ser aplicados em caso de nova tentativa de entrega.", en: "Additional costs may apply in case of a new delivery attempt.", fr: "Des frais supplémentaires peuvent s'appliquer en cas de nouvelle tentative de livraison.", de: "Bei einem erneuten Zustellversuch können zusätzliche Kosten anfallen." },

  // S7 - Mercadorias Proibidas
  "reg.s7_title": { pt: "Mercadorias Proibidas", en: "Prohibited Goods", fr: "Marchandises Interdites", de: "Verbotene Waren" },
  "reg.s7_intro": { pt: "A empresa não transporta, salvo acordo prévio e autorização legal:", en: "The company does not transport, except by prior agreement and legal authorization:", fr: "L'entreprise ne transporte pas, sauf accord préalable et autorisation légale :", de: "Das Unternehmen transportiert nicht, außer nach vorheriger Vereinbarung und gesetzlicher Genehmigung:" },
  "reg.s7_a": { pt: "Substâncias ilícitas", en: "Illicit substances", fr: "Substances illicites", de: "Illegale Substanzen" },
  "reg.s7_b": { pt: "Armas de fogo ou munições", en: "Firearms or ammunition", fr: "Armes à feu ou munitions", de: "Schusswaffen oder Munition" },
  "reg.s7_c": { pt: "Animais vivos", en: "Live animals", fr: "Animaux vivants", de: "Lebende Tiere" },
  "reg.s7_d": { pt: "Dinheiro em numerário", en: "Cash money", fr: "Argent liquide", de: "Bargeld" },
  "reg.s7_e": { pt: "Metais preciosos", en: "Precious metals", fr: "Métaux précieux", de: "Edelmetalle" },
  "reg.s7_f": { pt: "Joias ou objetos de elevado valor não declarados", en: "Jewelry or undeclared high-value objects", fr: "Bijoux ou objets de grande valeur non déclarés", de: "Schmuck oder nicht deklarierte Wertgegenstände" },
  "reg.s7_g": { pt: "Materiais explosivos, inflamáveis ou corrosivos", en: "Explosive, flammable or corrosive materials", fr: "Matériaux explosifs, inflammables ou corrosifs", de: "Explosive, brennbare oder ätzende Materialien" },
  "reg.s7_h": { pt: "Substâncias perigosas", en: "Dangerous substances", fr: "Substances dangereuses", de: "Gefährliche Substanzen" },
  "reg.s7_i": { pt: "Baterias de lítio soltas", en: "Loose lithium batteries", fr: "Batteries au lithium en vrac", de: "Lose Lithiumbatterien" },
  "reg.s7_j": { pt: "Equipamentos eletrónicos mal acondicionados", en: "Poorly packaged electronic equipment", fr: "Équipements électroniques mal conditionnés", de: "Schlecht verpackte Elektronikgeräte" },
  "reg.s7_k": { pt: "Vidro solto ou objetos frágeis sem proteção adequada", en: "Loose glass or fragile objects without adequate protection", fr: "Verre en vrac ou objets fragiles sans protection adéquate", de: "Loses Glas oder zerbrechliche Gegenstände ohne ausreichenden Schutz" },
  "reg.s7_l": { pt: "Qualquer mercadoria cuja circulação seja proibida por lei.", en: "Any goods whose circulation is prohibited by law.", fr: "Toute marchandise dont la circulation est interdite par la loi.", de: "Jede Ware, deren Umlauf gesetzlich verboten ist." },
  "reg.s7_outro": { pt: "A empresa reserva-se ao direito de recusar transporte de qualquer mercadoria que considere inadequada ou perigosa.", en: "The company reserves the right to refuse transport of any goods it deems inadequate or dangerous.", fr: "L'entreprise se réserve le droit de refuser le transport de toute marchandise qu'elle juge inadéquate ou dangereuse.", de: "Das Unternehmen behält sich das Recht vor, den Transport von Waren abzulehnen, die es als ungeeignet oder gefährlich erachtet." },

  // S8 - Documentação
  "reg.s8_title": { pt: "Documentação da Mercadoria", en: "Goods Documentation", fr: "Documentation de la Marchandise", de: "Warendokumentation" },
  "reg.s8_intro": { pt: "Quando a mercadoria estiver associada a atividade comercial, o remetente deve fornecer os documentos legalmente exigidos, nomeadamente:", en: "When the goods are associated with commercial activity, the sender must provide the legally required documents, namely:", fr: "Lorsque la marchandise est associée à une activité commerciale, l'expéditeur doit fournir les documents légalement requis, notamment :", de: "Wenn die Ware mit einer gewerblichen Tätigkeit verbunden ist, muss der Absender die gesetzlich erforderlichen Dokumente vorlegen, insbesondere:" },
  "reg.s8_a": { pt: "Guia de transporte", en: "Transport guide", fr: "Guide de transport", de: "Transportschein" },
  "reg.s8_b": { pt: "Guia de remessa", en: "Dispatch note", fr: "Bordereau d'expédition", de: "Versandschein" },
  "reg.s8_c": { pt: "Fatura", en: "Invoice", fr: "Facture", de: "Rechnung" },
  "reg.s8_d": { pt: "Outros documentos exigidos pela legislação aplicável.", en: "Other documents required by applicable legislation.", fr: "Autres documents exigés par la législation applicable.", de: "Andere nach geltendem Recht erforderliche Dokumente." },
  "reg.s8_outro": { pt: "O remetente é responsável pela legalidade e veracidade da documentação fornecida.", en: "The sender is responsible for the legality and accuracy of the documentation provided.", fr: "L'expéditeur est responsable de la légalité et de la véracité de la documentation fournie.", de: "Der Absender ist für die Rechtmäßigkeit und Richtigkeit der bereitgestellten Dokumentation verantwortlich." },

  // S9 - Reclamações
  "reg.s9_title": { pt: "Reclamações", en: "Complaints", fr: "Réclamations", de: "Beschwerden" },
  "reg.s9_a": { pt: "Qualquer dano ou irregularidade deve ser comunicado no momento da entrega ou no prazo máximo de 24 horas após a receção da mercadoria.", en: "Any damage or irregularity must be reported at the time of delivery or within 24 hours of receiving the goods.", fr: "Tout dommage ou irrégularité doit être signalé au moment de la livraison ou dans les 24 heures suivant la réception de la marchandise.", de: "Schäden oder Unregelmäßigkeiten müssen bei der Lieferung oder innerhalb von 24 Stunden nach Wareneingang gemeldet werden." },
  "reg.s9_b": { pt: "A empresa poderá solicitar: fotografias, vídeos ou documentos comprovativos.", en: "The company may request: photographs, videos or supporting documents.", fr: "L'entreprise pourra demander : photographies, vidéos ou documents justificatifs.", de: "Das Unternehmen kann Fotos, Videos oder Belege anfordern." },
  "reg.s9_c": { pt: "Cada situação será analisada individualmente.", en: "Each situation will be analyzed individually.", fr: "Chaque situation sera analysée individuellement.", de: "Jede Situation wird individuell analysiert." },

  // S10 - Armazéns
  "reg.s10_title": { pt: "Armazéns", en: "Warehouses", fr: "Entrepôts", de: "Lager" },
  "reg.s10_a": { pt: "A empresa dispõe de armazéns em: Portugal, Luxemburgo e França (zona de fronteira).", en: "The company has warehouses in: Portugal, Luxembourg and France (border area).", fr: "L'entreprise dispose d'entrepôts au : Portugal, Luxembourg et France (zone frontalière).", de: "Das Unternehmen verfügt über Lager in: Portugal, Luxemburg und Frankreich (Grenzgebiet)." },
  "reg.s10_b": { pt: "Os horários, moradas e contactos encontram-se disponíveis no website oficial da empresa.", en: "Schedules, addresses and contacts are available on the company's official website.", fr: "Les horaires, adresses et contacts sont disponibles sur le site officiel de l'entreprise.", de: "Öffnungszeiten, Adressen und Kontakte sind auf der offiziellen Website des Unternehmens verfügbar." },
  "reg.s10_c": { pt: "A permanência de mercadorias em armazém poderá implicar custos de armazenamento, quando excedido um período razoável.", en: "Storing goods in the warehouse may incur storage costs when a reasonable period is exceeded.", fr: "Le stockage de marchandises en entrepôt pourra entraîner des frais de stockage lorsqu'un délai raisonnable est dépassé.", de: "Die Lagerung von Waren im Lager kann Lagerkosten verursachen, wenn ein angemessener Zeitraum überschritten wird." },

  // S11 - Confidencialidade
  "reg.s11_title": { pt: "Confidencialidade e Proteção de Dados", en: "Confidentiality and Data Protection", fr: "Confidentialité et Protection des Données", de: "Vertraulichkeit und Datenschutz" },
  "reg.s11_intro": { pt: "Os dados pessoais dos clientes são utilizados exclusivamente para:", en: "Customers' personal data is used exclusively for:", fr: "Les données personnelles des clients sont utilisées exclusivement pour :", de: "Die persönlichen Daten der Kunden werden ausschließlich verwendet für:" },
  "reg.s11_a": { pt: "Gestão logística", en: "Logistics management", fr: "Gestion logistique", de: "Logistikmanagement" },
  "reg.s11_b": { pt: "Comunicação relativa aos envios", en: "Communication regarding shipments", fr: "Communication relative aux envois", de: "Kommunikation bezüglich Sendungen" },
  "reg.s11_c": { pt: "Cumprimento de obrigações legais.", en: "Compliance with legal obligations.", fr: "Respect des obligations légales.", de: "Erfüllung gesetzlicher Pflichten." },
  "reg.s11_d": { pt: "A empresa cumpre o disposto no General Data Protection Regulation (GDPR/RGPD).", en: "The company complies with the General Data Protection Regulation (GDPR).", fr: "L'entreprise respecte le Règlement Général sur la Protection des Données (RGPD).", de: "Das Unternehmen hält die Datenschutz-Grundverordnung (DSGVO) ein." },
  "reg.s11_e": { pt: "Os dados não serão partilhados com terceiros, salvo obrigação legal ou necessidade operacional do serviço.", en: "Data will not be shared with third parties, except by legal obligation or operational need of the service.", fr: "Les données ne seront pas partagées avec des tiers, sauf obligation légale ou nécessité opérationnelle du service.", de: "Daten werden nicht an Dritte weitergegeben, außer bei gesetzlicher Verpflichtung oder betrieblicher Notwendigkeit." },

  // S12 - CMR
  "reg.s12_title": { pt: "Limite de Responsabilidade e Convenção CMR", en: "Liability Limits and CMR Convention", fr: "Limite de Responsabilité et Convention CMR", de: "Haftungsbeschränkung und CMR-Übereinkommen" },
  "reg.s12_a": { pt: "Os transportes rodoviários internacionais estão sujeitos à Convention on the Contract for the International Carriage of Goods by Road (CMR).", en: "International road transport is subject to the Convention on the Contract for the International Carriage of Goods by Road (CMR).", fr: "Les transports routiers internationaux sont soumis à la Convention relative au contrat de transport international de marchandises par route (CMR).", de: "Der internationale Straßengüterverkehr unterliegt dem Übereinkommen über den Beförderungsvertrag im internationalen Straßengüterverkehr (CMR)." },
  "reg.s12_b": { pt: "A responsabilidade do transportador está limitada a 8,33 Direitos de Saque Especiais (SDR) por quilograma de peso bruto da mercadoria perdida ou danificada.", en: "The carrier's liability is limited to 8.33 Special Drawing Rights (SDR) per kilogram of gross weight of goods lost or damaged.", fr: "La responsabilité du transporteur est limitée à 8,33 Droits de Tirage Spéciaux (DTS) par kilogramme de poids brut de la marchandise perdue ou endommagée.", de: "Die Haftung des Frachtführers ist auf 8,33 Sonderziehungsrechte (SZR) pro Kilogramm Bruttogewicht der verlorenen oder beschädigten Ware beschränkt." },
  "reg.s12_c": { pt: "Salvo declaração de valor previamente aceite ou contratação de seguro adicional.", en: "Except for a prior accepted declaration of value or additional insurance.", fr: "Sauf déclaration de valeur préalablement acceptée ou souscription d'une assurance complémentaire.", de: "Außer bei vorheriger akzeptierter Wertdeklaration oder zusätzlicher Versicherung." },
  "reg.s12_d": { pt: "Na ausência de declaração de valor, a indemnização estará limitada aos valores previstos pela CMR.", en: "In the absence of a declaration of value, compensation will be limited to the amounts provided by the CMR.", fr: "En l'absence de déclaration de valeur, l'indemnisation sera limitée aux montants prévus par la CMR.", de: "Ohne Wertdeklaration ist die Entschädigung auf die von der CMR vorgesehenen Beträge beschränkt." },
  "reg.s12_e": { pt: "O seguro de responsabilidade do transportador cobre apenas os limites legais aplicáveis.", en: "The carrier's liability insurance covers only the applicable legal limits.", fr: "L'assurance responsabilité du transporteur ne couvre que les limites légales applicables.", de: "Die Haftpflichtversicherung des Frachtführers deckt nur die geltenden gesetzlichen Grenzen ab." },

  // S13 - Declaração de Valor e Seguro
  "reg.s13_title": { pt: "Declaração de Valor e Seguro de Mercadorias", en: "Declaration of Value and Goods Insurance", fr: "Déclaration de Valeur et Assurance des Marchandises", de: "Wertdeklaration und Warenversicherung" },
  "reg.s13_a": { pt: "Caso o cliente pretenda cobertura pelo valor total da mercadoria, deverá solicitar previamente: declaração de valor ou seguro adicional.", en: "If the customer requires coverage for the full value of the goods, they must request in advance: a declaration of value or additional insurance.", fr: "Si le client souhaite une couverture pour la valeur totale de la marchandise, il doit demander au préalable : une déclaration de valeur ou une assurance complémentaire.", de: "Wenn der Kunde eine Deckung für den vollen Warenwert wünscht, muss er vorab beantragen: eine Wertdeklaration oder eine Zusatzversicherung." },
  "reg.s13_b": { pt: "Este serviço pode implicar custos adicionais.", en: "This service may incur additional costs.", fr: "Ce service peut entraîner des frais supplémentaires.", de: "Dieser Service kann zusätzliche Kosten verursachen." },
  "reg.s13_c": { pt: "Na ausência destes, aplica-se o limite legal de responsabilidade.", en: "In the absence of these, the legal liability limit applies.", fr: "En l'absence de ceux-ci, la limite légale de responsabilité s'applique.", de: "Ohne diese gilt die gesetzliche Haftungsgrenze." },

  // S14 - Força Maior
  "reg.s14_title": { pt: "Força Maior", en: "Force Majeure", fr: "Force Majeure", de: "Höhere Gewalt" },
  "reg.s14_intro": { pt: "A empresa não será responsável por atrasos ou incumprimentos causados por circunstâncias fora do seu controlo, incluindo:", en: "The company shall not be liable for delays or non-compliance caused by circumstances beyond its control, including:", fr: "L'entreprise ne sera pas responsable des retards ou manquements causés par des circonstances indépendantes de sa volonté, notamment :", de: "Das Unternehmen haftet nicht für Verzögerungen oder Nichterfüllung aufgrund von Umständen außerhalb seiner Kontrolle, einschließlich:" },
  "reg.s14_a": { pt: "Acidentes", en: "Accidents", fr: "Accidents", de: "Unfälle" },
  "reg.s14_b": { pt: "Condições meteorológicas extremas", en: "Extreme weather conditions", fr: "Conditions météorologiques extrêmes", de: "Extreme Wetterbedingungen" },
  "reg.s14_c": { pt: "Greves", en: "Strikes", fr: "Grèves", de: "Streiks" },
  "reg.s14_d": { pt: "Bloqueios rodoviários", en: "Road blockages", fr: "Blocages routiers", de: "Straßensperrungen" },
  "reg.s14_e": { pt: "Decisões governamentais", en: "Government decisions", fr: "Décisions gouvernementales", de: "Regierungsentscheidungen" },
  "reg.s14_f": { pt: "Outras situações de força maior.", en: "Other force majeure situations.", fr: "Autres situations de force majeure.", de: "Andere Situationen höherer Gewalt." },

  // S15 - Disposições Finais
  "reg.s15_title": { pt: "Disposições Finais", en: "Final Provisions", fr: "Dispositions Finales", de: "Schlussbestimmungen" },
  "reg.s15_a": { pt: "A empresa TRANSPORTES CARLOS & CÉSAR reserva-se o direito de alterar o presente regulamento a qualquer momento.", en: "TRANSPORTES CARLOS & CÉSAR reserves the right to modify these regulations at any time.", fr: "TRANSPORTES CARLOS & CÉSAR se réserve le droit de modifier le présent règlement à tout moment.", de: "TRANSPORTES CARLOS & CÉSAR behält sich das Recht vor, diese Verordnung jederzeit zu ändern." },
  "reg.s15_b": { pt: "As alterações entram em vigor após publicação no website oficial da empresa.", en: "Changes take effect after publication on the company's official website.", fr: "Les modifications entrent en vigueur après publication sur le site officiel de l'entreprise.", de: "Änderungen treten nach Veröffentlichung auf der offiziellen Website des Unternehmens in Kraft." },
  "reg.s15_c": { pt: "A utilização dos serviços implica a aceitação integral do regulamento em vigor.", en: "The use of services implies full acceptance of the regulations in force.", fr: "L'utilisation des services implique l'acceptation intégrale du règlement en vigueur.", de: "Die Nutzung der Dienste impliziert die vollständige Akzeptanz der geltenden Verordnung." },

  // Congelados info page
  "cong.title": { pt: "Serviço de Congelados", en: "Frozen Goods Service", fr: "Service Surgelés", de: "Tiefkühlservice" },
  "cong.intro": { pt: "Realizamos transporte de mercadoria congelada entre Portugal e o Luxemburgo, em camião frigorífico com todas as condições térmicas necessárias para garantir que a sua mercadoria chega ao destino em perfeitas condições.", en: "We transport frozen goods between Portugal and Luxembourg in a refrigerated truck with all the necessary thermal conditions to ensure your goods arrive in perfect condition.", fr: "Nous transportons des marchandises surgelées entre le Portugal et le Luxembourg dans un camion frigorifique avec toutes les conditions thermiques nécessaires.", de: "Wir transportieren Tiefkühlware zwischen Portugal und Luxemburg in einem Kühlwagen mit allen notwendigen thermischen Bedingungen." },
  "cong.schedule_title": { pt: "Agende com antecedência", en: "Schedule in advance", fr: "Planifiez à l'avance", de: "Planen Sie im Voraus" },
  "cong.schedule_desc": { pt: "O envio de congelados deve ser agendado com o máximo de antecedência possível, por telefone ou WhatsApp. Assim garantimos espaço no camião frigorífico e o melhor serviço para a sua mercadoria.", en: "Frozen shipments must be scheduled as far in advance as possible, by phone or WhatsApp. This ensures space in the refrigerated truck and the best service for your goods.", fr: "Les envois surgelés doivent être planifiés le plus tôt possible, par téléphone ou WhatsApp. Cela garantit de l'espace dans le camion et le meilleur service.", de: "Tiefkühlsendungen müssen so früh wie möglich per Telefon oder WhatsApp geplant werden, um Platz im Kühlwagen und den besten Service zu gewährleisten." },
  "cong.packaging_title": { pt: "Embalamento adequado", en: "Proper packaging", fr: "Emballage approprié", de: "Geeignete Verpackung" },
  "cong.packaging_desc": { pt: "A mercadoria congelada deve estar devidamente acondicionada dentro de embalagens térmicas adequadas, como caixas de esferovite, arcas térmicas ou sacos térmicos. O cliente é responsável pela correta embalagem dos seus produtos.", en: "Frozen goods must be properly packed in suitable thermal packaging, such as polystyrene boxes, thermal coolers or thermal bags. The customer is responsible for proper packaging.", fr: "Les marchandises surgelées doivent être correctement conditionnées dans des emballages thermiques adaptés : boîtes en polystyrène, glacières thermiques ou sacs thermiques. Le client est responsable du bon emballage.", de: "Tiefkühlware muss in geeigneten Thermoverpackungen wie Styroporboxen, Kühlboxen oder Thermobeuteln verpackt sein. Der Kunde ist für die korrekte Verpackung verantwortlich." },
  "cong.transport_title": { pt: "Transporte frigorífico", en: "Refrigerated transport", fr: "Transport frigorifique", de: "Kühltransport" },
  "cong.transport_desc": { pt: "O transporte é realizado em camião frigorífico, com temperatura controlada durante todo o trajeto. A mercadoria viaja em condições térmicas adequadas para chegar ao destino em perfeitas condições de conservação.", en: "Transport is carried out in a refrigerated truck with controlled temperature throughout the journey. Goods travel in proper thermal conditions to arrive at their destination in perfect preservation.", fr: "Le transport est effectué en camion frigorifique, avec une température contrôlée tout au long du trajet. Les marchandises voyagent dans des conditions thermiques optimales.", de: "Der Transport erfolgt im Kühlwagen mit kontrollierter Temperatur während der gesamten Fahrt. Die Waren reisen unter optimalen Bedingungen." },
  "cong.pickup_title": { pt: "Levantamento no destino", en: "Pickup at destination", fr: "Retrait à destination", de: "Abholung am Ziel" },
  "cong.pickup_desc": { pt: "A mercadoria congelada deve ser levantada no destino entre as 16:00 e as 18:30 do dia de chegada. É fundamental respeitar este horário para garantir a qualidade e conservação dos produtos.", en: "Frozen goods must be picked up at the destination between 4:00 PM and 6:30 PM on the day of arrival. It is essential to respect this schedule to ensure product quality and preservation.", fr: "Les marchandises surgelées doivent être retirées à destination entre 16h00 et 18h30 le jour d'arrivée. Il est essentiel de respecter cet horaire pour garantir la qualité des produits.", de: "Tiefkühlware muss am Zielort zwischen 16:00 und 18:30 Uhr am Ankunftstag abgeholt werden. Die Einhaltung dieses Zeitplans ist entscheidend für die Produktqualität." },
  // Testimonials
  "testimonials.title": { pt: "O que os nossos clientes dizem", en: "What our clients say", fr: "Ce que disent nos clients", de: "Was unsere Kunden sagen" },
  "testimonials.t1": { pt: "O melhor transporte Portugal-Luxemburgo. Simpatia, cuidado e profissionalismo. Ao fim de 7 anos de transportes, criou-se naturalmente uma amizade pela sensação de família que é esta empresa.", en: "The best transport Portugal-Luxembourg. Kindness, care and professionalism. After 7 years, a natural friendship was born from the family feeling of this company.", fr: "Le meilleur transport Portugal-Luxembourg. Gentillesse, soin et professionnalisme. Après 7 ans, une amitié naturelle est née du sentiment familial de cette entreprise.", de: "Der beste Transport Portugal-Luxemburg. Freundlichkeit, Sorgfalt und Professionalität. Nach 7 Jahren entstand eine natürliche Freundschaft durch das familiäre Gefühl dieses Unternehmens." },
  "testimonials.t2": { pt: "Há 9 anos com vocês e sempre sem problemas. Recomendo!", en: "9 years with you and never a problem. Highly recommend!", fr: "9 ans avec vous et jamais un problème. Je recommande !", de: "9 Jahre bei euch und nie ein Problem. Sehr empfehlenswert!" },
  "testimonials.t3": { pt: "Já enviei muita mercadoria e chegou tudo a tempo e em ótimo estado. Pessoas 5 estrelas e sempre com todo o cuidado. Aconselho vivamente!", en: "I've sent lots of goods and everything arrived on time and in great condition. 5-star people, always careful. Highly recommended!", fr: "J'ai envoyé beaucoup de marchandises et tout est arrivé à temps et en excellent état. Des gens 5 étoiles, toujours attentionnés. Vivement recommandé !", de: "Ich habe viele Waren verschickt und alles kam pünktlich und in bestem Zustand an. 5-Sterne-Leute, immer sorgfältig. Sehr empfehlenswert!" },
  "testimonials.t4": { pt: "Um sincero agradecimento à Empresa de Transportes Carlos e César pelo apoio no transporte de materiais doados à nossa instituição em Mortágua.", en: "A sincere thank you to Transportes Carlos e César for supporting the transport of donated materials to our institution in Mortágua.", fr: "Un sincère remerciement à Transportes Carlos e César pour le soutien au transport de matériaux donnés à notre institution à Mortágua.", de: "Ein herzliches Dankeschön an Transportes Carlos e César für die Unterstützung beim Transport gespendeter Materialien an unsere Einrichtung in Mortágua." },
  "testimonials.t5": { pt: "Eficácia, competência e responsabilidade. Bom atendimento, 5 estrelas!", en: "Efficiency, competence and responsibility. Great service, 5 stars!", fr: "Efficacité, compétence et responsabilité. Excellent service, 5 étoiles !", de: "Effizienz, Kompetenz und Verantwortung. Toller Service, 5 Sterne!" },
} as const;

export type TranslationKey = keyof typeof translations;

export function t(key: TranslationKey, lang: Lang): string {
  return translations[key]?.[lang] ?? translations[key]?.pt ?? key;
}

// Date locale mapping
export const DATE_LOCALES: Record<Lang, string> = {
  pt: "pt-PT",
  en: "en-GB",
  fr: "fr-FR",
  de: "de-DE",
};
